#!/usr/bin/env bun
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const pkg = JSON.parse(
	readFileSync(join(process.cwd(), "package.json"), "utf-8"),
);
const content = `// Auto-generated by build script. DO NOT EDIT.
export const VERSION = "${pkg.version}";
`;
writeFileSync(join(process.cwd(), "src/version.const.ts"), content);
console.log(`Generated version.const.ts with version ${pkg.version}`);
